### ISSUE TITLE
Bot is not react to my commands

### ISSUE THREAD

**Issue by Tar4s** [rubenlagus/TelegramBots#207]
I've long polling implementation and two background thread workers.
Bot almost always works fine, but sometimes it don't react to my commands within 2-3 minutes several times a day! And I have no idea what's going on. Please help!

**Comment by MonsterDeveloper** [comment]
Try to revoke your bot's token with BotFather.

**Comment by Tar4s** [comment]
thanks, I'll try

But specifically what is the reason?

**Comment by Tar4s** [comment]
И нахуя мы по английски пишем, если ты из Москвы а я из Питера...

**Comment by MonsterDeveloper** [comment]
@Tar4s To keep repo english 😆 So everyone can understand 😃

**Comment by rubenlagus** [comment]
@Tar4s Do you get any error or exception?

**Comment by Tar4s** [comment]
No. Bot just stop receiving messages

**Comment by rubenlagus** [comment]
What about logs? Anything at all? Sound really weird.

**Comment by Tar4s** [comment]
@rubenlagus Yes, it's very strange. The fact is that it is difficult to catch, it appears on its own. I execute the command, but onUpdateReceived does not respond.

An hour ago, it happened again. I quickly disconnected from the server and launched the bot from my computer and the bot responded to my commands. After that, I changed the server's location to western Europe and the bot responded faster to commands, perhaps its geo-location could influence this error, just how? I can not say ...

So far, everything, I'll keep in touch.

**Comment by rubenlagus** [comment]
May be some kind of network problem. In case of that there will be a Exponential Backoff that may looks like it. But in that case, you should see something in log file (if you are using it).

**Comment by Tar4s** [comment]
@rubenlagus it's again. near 10:30 (UTC+3) bot stop receiving messages. **BotLogger** don't write anything, and **onUpdateReceived** is quiet, but ... worked after restart =(

**Comment by biagio91** [comment]
Hi, I'm encountering the same problem: sometimes, randomly, my bot (which uses long polling) just hangs. I don't get any error or exception (except _**"TelegramApiRequestException: Error answering callback query: [400] Bad Request: QUERY_ID_INVALID"**_, but that's because of the bot hanging and consequently not answering to the callback query in time). I've added further logging instructions (because, like Tar4s, I couldn't catch the problem with debugger) and I've noticed that the bot hangs when doing an **HTTP POST** request (sometimes the one for invoking API methods like 'answerCallbackQuery' or 'editMessageText', sometimes the one in the ReaderThread in DefaultBotSession.java looking for updates, although updates are available). Apart from the answerCallbackQuery which, like I previously said, gets an **HTTP 400** response, all other methods' invocations result in an **HTTP 200** response, despite taking 2-3 minutes or more to be completed.

**Comment by Tar4s** [comment]
@biagio91 Good job! Perhaps your information will help @rubenlagus to analyze this situation more carefully

By the way, in your backend code you're have backgound thread workers (implements from Runnable, or something like this)?

**Comment by biagio91** [comment]
@Tar4s I'm using this API inside a Java Enterprise project, and my bot is implemented as a Stateless session bean.

**Comment by Tar4s** [comment]
I'm using a virtual machine on [MS Azure](http://www.azure.microsoft.com). Today I noticed a strange thing. I **could not ping any address** from my virtual machine, not one. As the bot could send messages - I do not know. It is clear that this should not be so. In the settings I found the item that I specified in the screenshot, after it was turned on and the VDS was rebooted, there were **no breaks** and all public addresses are pinged. By the end of the day, if stability continues, I will close the issue

![This](http://i.imgur.com/QmUwByo.png)

**Comment by Tar4s** [comment]
Problem is solved

**Comment by biagio91** [comment]
I'm still encountering the problem. With eclipse debugger, using exception breakpoints, I'm getting SocketTimeoutException. Problem happens mostly with the HttpClient in DefaultAbsSender, Http requests sent with the HttpClient in ReaderThread work almost fine

**Comment by rubenlagus** [comment]
It may be related with #202, hopefully it should be fixed with next version.
